site_name: scmRTOS
#site_url: ''
#use_directory_urls: false

theme:
    name: readthedocs
    max_width: 2000
    navigation_depth: 5
    font: false
    features:
        - content.code.copy
        - content.code.annotate
    #name: windmill

extra_css: 
    - extra.css


nav:
    - Intro:
        - Instead of a preface           : index.md 
        - Overview                       : src/overview.md
    - RTOS Components:
        - Kernel                         : src/kernel.md
        - Processes                      : src/processes.md
        - Interprocess Communications    : src/ipcs.md
        - Ports                          : src/ports.md

    - Appendix:
        - Debug                          : src/debug.md
        - Process Performance Profiling  : src/profiler.md
        - Glossary                       : src/glossary.md

extra_javascript:
    - js/mathjax.js
    - js/mathjax/tex-mml-chtml.js
    - js/wavedrom.min.js
    - js/wavedrom_loader.js
    - js/wavedrom.unpkg.js
    - js/wavedrom_skin_default.js


markdown_extensions:
    - toc:
        permalink: "ðŸ”—"
        baselevel: 1
    - pymdownx.arithmatex:
       generic: true    
    - admonition
    - attr_list
    - footnotes
    - markdown_wavedrom
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tilde
    - pymdownx.betterem
    - pymdownx.blocks.caption
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.snippets

plugins:
    - search:
        lang: ru

    - glightbox
    #- markdownwavedrom
